VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "View"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"No"
Private ViewMatrix As D3DMATRIX

Public Function GetViewMatrix() As D3DMATRIX
    GetViewMatrix = ViewMatrix
End Function

Public Sub SetViewMatrix(MatrixIndex As Integer)
    ViewMatrix = Matrices(MatrixIndex)
End Sub

